---

- name: Clean binary to replace new one
  file: state=absent path="{{ item }}"
  with_items:
    - "{{dest_path}}"
    - "{{temp_path}}/{{source_code}}"
  register: clean_binary

- name: copy binary
  copy: src="{{ source_code }}"  dest="{{temp_path}}"
  register: copy_binary
  when: clean_binary|succeeded

- name: Creates dest directory for dest folder
  file: path={{ dest_path }} state=directory

- name : Unarchive source code
  unarchive: src="{{temp_path}}/{{source_code}}" dest="{{dest_path}}" remote_src=true
  register: unarchive_sourcecode
  when: copy_binary|succeeded

# failed when pm2 haven't started yet. so for this purpose, ignore it. 
- name: Reload NodeJS
  command: pm2 reload all
  register: pm2_reload
  failed_when: false
  changed_when: false

# it will start if reload failed. 
- name: Restart NodeJS with cluster mode
  command: pm2 start server.js -i 0 chdir={{ dest_path }}/src
  register: restart_pm2
  when: not pm2_reload|succeeded

