---

- include: "installer.yml"
  static: yes
  tags: install

- include: "nodejs.yml"
  static: yes
  tags: install

- include: "npmbox.yml"
  static: yes
  tags: install

- include: "pm2.yml"
  static: yes
  tags: install
   
- include: "deployment.yml"
  static: yes
  tags: deploy
