---

- name: kill pm2 
  command: pm2 kill
  tags: force_start

- name: Restart NodeJS
  command: pm2 start {{ dest_path }}/src/{{ pm2_server }}
  tags: force_start

- name: reload pm2 
  command: pm2 reload all
  tags: reload

- name: Restart NodeJS
  command: pm2 restart {{ dest_path }}/src/{{ pm2_server }}
  when: pm2_reload|failed
  tags: restart